substitutions:
  device: livingroom
  name: Living Room

esphome:
  name: ${device}

esp32:
  board: m5stack-atom
  framework:
    type: arduino

# Enable logging
logger:

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Fallback Hotspot"
    password: "gYut3Rn1aX4B"

#  manual_ip:
#    # Set this to the IP of the ESP
#    static_ip: 192.168.1.190
#    # Set this to the IP address of the router. Often ends with .1
#    gateway: 192.168.1.1
#    # The subnet of the network. 255.255.255.0 works for most home networks.
#    subnet: 255.255.255.0

captive_portal:

light:
  - name: ${name} Light
    platform: fastled_clockless
    chipset: SK6812
    pin: 27
    num_leds: 1
    rgb_order: GRB
    id: status_led

binary_sensor:
  - name: ${name} Button
    platform: gpio
    pin:
      number: 39
      inverted: true
    on_press:
      then:
        - mqtt.publish:
            topic: accel_x
            payload: !lambda "return to_string(id(accel_x).state);"

i2c:
  sda: 26
  scl: 32
  scan: true

sensor:
  - platform: mpu6886
    address: 0x68
    update_interval: 1000ms
    accel_x:
      name: "${name} Accel X"
      id: accel_x
      on_value:
        then:
          - mqtt.publish:
              topic: accel_x
              payload: !lambda "return to_string(x);"
    accel_y:
      name: "${name} Accel Y"
#    accel_z:
#      name: "${name} Accel z"
#    gyro_x:
#      name: "${name} Gyro X"
#    gyro_y:
#      name: "${name} Gyro Y"
#    gyro_z:
#      name: "${name} Gyro z"
#    temperature:
#      name: "${name} Temperature"


