substitutions:
  device_name: dimmer1
  friendly_name: Dimmer 1

esphome:
  name: ${device_name}

esp32:
  board: m5stack-atom
  framework:
    type: arduino

#light:
#  - name: ${name} Light
#    platform: fastled_clockless
#    chipset: SK6812
#    pin: 27
#    num_leds: 1
#    rgb_order: GRB
#    id: status_led

#mqtt:
#  broker: pi1.lan
#  on_message:
#    topic: dimmer1
#    then:
#      - light.toggle:
#          id: status_led
#          transition_length: 0s

output:
  - platform: ledc
    pin: GPIO22
    id: gpio_22
    frequency: 1220Hz

light:
  - platform: monochromatic
    output: gpio_22
    name: ${friendly_name} Light
    id: dimmer

mqtt:
  broker: pi1.lan
  on_message:
    topic: dimmer1
    then:
      - light.turn_on:
          id: dimmer
          brightness: !lambda "return atoi(x.c_str()) / 100000.0;"
          transition_length: 0s

logger:
  #level: NONE

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: "hogxyvZGcsFa"

captive_portal:



binary_sensor:
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: ${friendly_name} Button
    on_press:
      then:
        - light.toggle:
            id: dimmer
            transition_length: 0s
